name: Deploy to Azure Static Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        default: "dev"
        options:
            - "dev"
            - "stage"
            - "production"

jobs:
  crate_and_deploy:
    name: Create or Update and Deploy Static Web App
    runs-on: ubuntu-latest
    steps:

    - name: Set default deploy environment
      run: |
        if [ -z "${{ inputs.environment }}" ]
        then
          echo "DEPLOY_ENV=dev" >> $GITHUB_ENV
        else
          echo "DEPLOY_ENV=${{ inputs.environment }}" >> $GITHUB_ENV
        fi
      
    - name: Set resource group environment name
      run: |
        echo "RESOURCEGROUP_NAME=${{ env.DEPLOY_ENV }}-${{ secrets.AZURE_RG }}-rg" >> $GITHUB_ENV

    # Checkout code
    - uses: actions/checkout@main

    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Get resource group location
    - name: Get resource group location
      run: |
        RESOURCEGROUP_LOCATION=$(az group show --name ${{ env.RESOURCEGROUP_NAME }} --query 'location' --output tsv)
        echo "RESOURCEGROUP_LOCATION=$RESOURCEGROUP_LOCATION" >> $GITHUB_ENV

    - name: Get SWA deployment token
      uses: azure/CLI@v1
      id: swa-token
      with:
        inlineScript: |
          SWA_DEPLOYMENT_TOKEN=$(az staticwebapp secrets list -n readread -o tsv --query properties.apiKey)
          echo "::add-mask::$SWA_DEPLOYMENT_TOKEN"
          echo SWA_DEPLOYMENT_TOKEN=$SWA_DEPLOYMENT_TOKEN >> $GITHUB_ENV

    - name: Create static web app
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        scope: resourcegroup
        resourceGroupName: ${{ env.RESOURCEGROUP_NAME }}
        parameters: location=${{ env.RESOURCEGROUP_LOCATION }} repoUrl=https://github.com/${{ github.repository }} token=${{ env.SWA_DEPLOYMENT_TOKEN }}
        template: ${{ github.workspace }}/infrastructure/app.bicep
        deploymentName: ${{ env.RESOURCEGROUP_NAME }}-${{ env.RESOURCEGROUP_LOCATION}}-deploy

    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ env.SWA_DEPLOYMENT_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
        action: "upload"
        app_location: "/app" # App source code path
        output_location: "/dist"
        routes_location: "/app"